#pragma once
/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "Gui\Knob.h"


//==============================================================================
/**
*/
class ObxdAudioProcessorEditor  :
	public AudioProcessorEditor//,
                    //      public ChangeListener,
                    //      public SliderListener,
					//	  public ButtonListener,
					//	  public ComboBoxListener,
					//	  public AudioProcessorListener

{
public:
    ObxdAudioProcessorEditor (ObxdAudioProcessor* ownerFilter);
    ~ObxdAudioProcessorEditor();

	    //==============================================================================
    /** Our demo filter is a ChangeBroadcaster, and will call us back when one of
        its parameters changes.
    */
    int changeListenerCallback (void* source);
    void sliderValueChanged (Slider*);
	void buttonClicked (Button *);
    void comboBoxChanged (ComboBox*);

    //==============================================================================
    /** Standard Juce paint callback. */
    void paint (Graphics& g);

    /** Standard Juce resize callback. */
    //void resized();
	Knob* cutoffKnob;
    //==============================================================================
    // This is just a standard Juce paint method...
//    void paint (Graphics& g);
	ObxdAudioProcessor* getFilter() noexcept    { return (ObxdAudioProcessor*)getAudioProcessor();}
};


#endif  // PLUGINEDITOR_H_INCLUDED
